controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# error:
#     path: /error/{code}
#     controller: App\Controller\DefaultController::error